# Generated by Django 5.2.17 on 2026-09-13 16:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('badge', models.CharField(default='</>', max_length=20)),
                ('description', models.TextField()),
                ('skills_list', models.CharField(help_text='Comma-separated list of skills, e.g. Python, Java, HTML5 & CSS3', max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
