# Generated by Django 5.2.17 on 2026-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_experience_ended_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='education',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
